# Generated by Django 5.1.3 on 2024-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ejemplos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
