# Generated by Django 5.1.3 on 2024-12-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_ejemplos_problem_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='ejemplos',
        ),
    ]
