# Generated by Django 5.1.2 on 2024-12-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_problem_ejemplos'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='time',
            field=models.IntegerField(default=15),
        ),
    ]
