import Image from "next/image";
import Link from "next/link";

const Header = () => {
  return (
      <header className="px-4 lg:px-6 h-20 flex items-center bg-tukeyPink dark:bg-tukeyPurple">
            <Link className="flex items-center justify-center" href="#">
                    <Image
                              src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Logo%20minimalista%202-07-OEU1robIuAWK1cxOlVfV918xQ3GlPU.png"
                                        alt="Tukey - Club de Ciencia de Datos Logo"
                                                  width={150}
                                                            height={60}
                                                                      className="h-12 w-auto"
                                                                              />
                                                                                    </Link>
                                                                                          <nav className="ml-auto flex gap-4 sm:gap-6 text-tukeyBlue">
                                                                                                  <Link
                                                                                                            className="text-sm font-medium hover:text-tukeyPurple underline-offset-4"
                                                                                                                      href="/features"
                                                                                                                              >
                                                                                                                                        Características
                                                                                                                                                </Link>
                                                                                                                                                        <Link
                                                                                                                                                                  className="text-sm font-medium hover:text-tukeyPurple underline-offset-4"
                                                                                                                                                                            href="/about"
                                                                                                                                                                                    >
                                                                                                                                                                                              Acerca de
                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                        className="text-sm font-medium hover:text-tukeyPurple underline-offset-4"
                                                                                                                                                                                                                                  href="/projects"
                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                    Proyectos
                                                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                              className="text-sm font-medium hover:text-tukeyPurple underline-offset-4"
                                                                                                                                                                                                                                                                                        href="/events"
                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                          Eventos
                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                          <Link
                                                                                                                                                                                                                                                                                                                                    className="text-sm font-medium hover:text-tukeyPurple underline-offset-4"
                                                                                                                                                                                                                                                                                                                                              href="/contact"
                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                Contacto
                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                              </nav>
                                                                                                                                                                                                                                                                                                                                                                                  </header>
                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                    export default Header;