# Generated by Django 5.1.3 on 2024-12-01 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='output',
            new_name='expected_output',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='is_public',
            new_name='visibility',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem'),
        ),
    ]
