# Generated by Django 5.1.3 on 2024-11-28 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usuarios', models.IntegerField(default=0)),
                ('total_ejercicios_resueltos', models.IntegerField(default=0)),
                ('promedio_tasa_exito', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('puntos_semanales', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
