# Generated by Django 5.1.3 on 2024-11-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticasglobales',
            old_name='promedio_tasa_exito',
            new_name='tasa_exito_global',
        ),
        migrations.RenameField(
            model_name='estadisticasglobales',
            old_name='total_ejercicios_resueltos',
            new_name='total_soluciones',
        ),
        migrations.RemoveField(
            model_name='sistemapuntos',
            name='puntos_semanales',
        ),
        migrations.RemoveField(
            model_name='sistemapuntos',
            name='puntos_totales',
        ),
        migrations.RemoveField(
            model_name='sistemapuntos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='sistemapuntos',
            name='nivel',
            field=models.CharField(default='Básico', max_length=50),
        ),
        migrations.AddField(
            model_name='sistemapuntos',
            name='puntos_requeridos',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
