# Generated by Django 5.1.3 on 2024-11-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_promedio_tasa_exito_estadisticasglobales_tasa_exito_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemapuntos',
            name='puntos_requeridos',
            field=models.IntegerField(default=100),
        ),
    ]
