# Generated by Django 5.1.3 on 2024-11-25 04:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models
import users.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('terms', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to=users.models.user_avatar_upload_path)),
                ('ejercicios_completados', models.IntegerField(default=0)),
                ('tasa_exito', models.FloatField(default=0.0)),
                ('last_exercise_date', models.DateField(blank=True, null=True)),
                ('racha', models.IntegerField(default=0)),
                ('tiempo_total', models.IntegerField(default=0)),
                ('ejercicios_resueltos_ultimos_siete_dias', models.JSONField(default=dict)),
                ('nivel', models.CharField(default='Básico', max_length=20)),
                ('puntos_experiencia', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
