# Generated by Django 5.1.3 on 2024-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_exercise_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
