# Generated by Django 5.1.3 on 2024-12-06 01:52

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_last_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to=users.models.user_avatar_upload_path),
        ),
    ]
