# Generated by Django 5.1.3 on 2024-12-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
