# Generated by Django 5.1.3 on 2024-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ejercicios_resueltos_ultimos_siete_dias',
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_exercises',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_solved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
    ]
