# Generated by Django 5.1.3 on 2024-12-01 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Pending', 'Pending'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Evaluation Failed', 'Evaluation Failed')], default='Pending', max_length=30)),
                ('output', models.TextField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('memory', models.FloatField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
