# Generated by Django 5.1.3 on 2024-12-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_category'),
        ('solutions', '0001_initial'),
        ('testcases', '0002_rename_output_testcase_expected_output_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='memory',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolutionTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Pending', 'Pending'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Evaluation Failed', 'Evaluation Failed')], max_length=30)),
                ('output', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField()),
                ('time', models.FloatField(blank=True, default=0.0, null=True)),
                ('memory', models.FloatField(blank=True, default=0.0, null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='solutions.solution')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase')),
            ],
        ),
    ]
