# Generated by Django 5.1.3 on 2024-12-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solution_status_alter_solution_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
