name: Clasificar Issues

on:
  issues:
    types: [opened, edited]

jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Analizar Issue
        id: analyze
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Analizando issue: ${{ github.event.issue.title }}"
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {"role": "system", "content": "Clasifica este issue en una de estas categorías: bug, feature, documentation, question"},
                {"role": "user", "content": "${{ github.event.issue.title }}\n${{ github.event.issue.body }}"}
              ]
            }')

          ANALYSIS=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "unclassified"')

          # Validar que ANALYSIS sea una categoría válida
          VALID_LABELS=("bug" "feature" "documentation" "question")
          if [[ ! " ${VALID_LABELS[@]} " =~ " ${ANALYSIS} " ]]; then
            echo "Categoría inválida recibida: $ANALYSIS. Asignando categoría 'unclassified'."
            ANALYSIS="unclassified"
          fi

          echo "label=$ANALYSIS" >> $GITHUB_ENV

      - name: Añadir Etiqueta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ env.label }}" != "unclassified" ]; then
            gh issue edit ${{ github.event.issue.number }} --add-label "${{ env.label }}"
          else
            echo "No se pudo determinar una etiqueta válida. El issue permanecerá sin clasificar."
          fi
