name: Lint Code Quality

on:
  pull_request:
    types: [opened, synchronize] # Se ejecuta al abrir o actualizar un PR
    branches:
      - main
      - diego

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install # Cambia por el gestor de tu proyecto (pip, yarn, etc.)

      - name: Run Linter
        run: npm run lint > lint-results.txt || true

      - name: Post Linter Results to Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DB_QUALITY }}
        run: |
          RESULTS=$(cat lint-results.txt)
          curl -X POST 'https://api.notion.com/v1/pages' \
          -H "Authorization: Bearer $NOTION_API_KEY" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "parent": { "database_id": "'"$NOTION_DATABASE_ID"'" },
            "properties": {
              "📝 Resultado del Linter": { "title": [{ "text": { "content": "Resultados de Linter: PR #'"${{ github.event.number }}"'" }}] },
              "📋 Detalles": { "rich_text": [{ "text": { "content": "'"$RESULTS"'" }}] },
              "📅 Fecha de Creación": { "date": { "start": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'" } }
            }
          }'
