name: Notion Commit Logger

on:
  push:
    branches:
      - main
      - 'diego'
  pull_request:
    types: [opened, closed]

jobs:
  log_to_notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log Commit to Notion
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: |
        # Instala cURL y jq para enviar datos a Notion
        sudo apt-get install -y jq

        # Obtén los detalles del commit
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        AUTHOR=$(git log -1 --pretty=%an)
        COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
        BRANCH=${{ github.ref }}

        # Crea la entrada en Notion
        curl -X POST "https://api.notion.com/v1/pages" \
        -H "Authorization: Bearer $NOTION_API_KEY" \
        -H "Content-Type: application/json" \
        -H "Notion-Version: 2022-06-28" \
        --data '{
          "parent": { "database_id": "'"$NOTION_DATABASE_ID"'" },
          "properties": {
            "Commit": { "title": [{ "text": { "content": "'"$COMMIT_MESSAGE"'" }}]},
            "Fecha": { "date": { "start": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'" }},
            "Autor": { "rich_text": [{ "text": { "content": "'"$AUTHOR"'" }}]},
            "URL": { "url": "'"$COMMIT_URL"'" },
            "Branch": { "rich_text": [{ "text": { "content": "'"$BRANCH"'" }}]}
          }
        }'
